"""empty message

Revision ID: 115b85e35c7
Revises: None
Create Date: 2014-07-04 10:55:34.403060

"""

# revision identifiers, used by Alembic.
revision = '115b85e35c7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
