"""empty message

Revision ID: 25c675edb52
Revises: 5385e5f7663
Create Date: 2014-09-07 14:12:56.669097

"""

# revision identifiers, used by Alembic.
revision = '25c675edb52'
down_revision = '5385e5f7663'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'url')
    ### end Alembic commands ###
