"""empty message

Revision ID: 269c78bcd7e
Revises: 25c675edb52
Create Date: 2015-02-23 15:43:41.005003

"""

# revision identifiers, used by Alembic.
revision = '269c78bcd7e'
down_revision = '25c675edb52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('language', sa.String(length=4), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'language')
    ### end Alembic commands ###
