"""empty message

Revision ID: 3b69f3756b7
Revises: 269c78bcd7e
Create Date: 2015-02-25 22:04:12.272507

"""

# revision identifiers, used by Alembic.
revision = '3b69f3756b7'
down_revision = '269c78bcd7e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name_en',
                                          sa.String(length=64),
                                          nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'name_en')
    ### end Alembic commands ###
