"""empty message

Revision ID: 3dc9c5ee9d8
Revises: 269c78bcd7e
Create Date: 2015-03-11 20:27:49.168609

"""

# revision identifiers, used by Alembic.
revision = '3dc9c5ee9d8'
down_revision = '269c78bcd7e'

from alembic import op
import sqlalchemy as sa
import datetime

Session = sa.orm.sessionmaker()

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    img = op.create_table('images_new',
                          sa.Column('id', sa.Integer, nullable=False),
                          sa.Column('filename', sa.String(120)),
                          sa.Column('file_url', sa.String(120)),
                          sa.Column('location', sa.String(120), nullable=False),
                          sa.Column('url', sa.String(120)),
                          sa.Column('type', sa.Integer, nullable=False),
                          sa.Column('active',
                                    sa.Boolean,
                                    nullable=False,
                                    default=False),
                          sa.Column('timestamp', sa.DateTime, nullable=False),

                          sa.PrimaryKeyConstraint('id'))

    bind = op.get_bind()

    results = bind.execute('select * from images').fetchall()
    images = [{'id': r[0],
               'filename': r[1],
               'file_url': '',
               'location': r[2],
               'url': r[3], # Change to 7 afterwards?
               'type': r[4],
               'active': r[5],
               'timestamp': datetime\
                   .datetime.strptime(r[6],
                                      '%Y-%m-%d %H:%M:%S.%f')} for r in results]
    op.bulk_insert(img, images)

    op.drop_table('images')
    op.rename_table('images_new', 'images')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    img = op.create_table('images_new',
                          sa.Column('id', sa.Integer, nullable=False),
                          sa.Column('filename', sa.String(120), nullable=False),
                          sa.Column('location', sa.String(120), nullable=False),
                          sa.Column('url', sa.String(120)),
                          sa.Column('type', sa.Integer, nullable=False),
                          sa.Column('active',
                                    sa.Boolean,
                                    nullable=False,
                                    default=False),
                          sa.Column('timestamp', sa.DateTime, nullable=False),

                          sa.PrimaryKeyConstraint('id'))

    bind = op.get_bind()

    results = bind.execute('select * from images').fetchall()
    images = [{'id': r[0],
               'filename': r[1],
               'location': r[3],
               'url': r[4], # Change to 7 afterwards?
               'type': r[5],
               'active': r[6],
               'timestamp': datetime\
                   .datetime.strptime(r[7],
                                      '%Y-%m-%d %H:%M:%S.%f')} for r in results
                   if r[1]]
    op.bulk_insert(img, images)

    op.drop_table('images')
    op.rename_table('images_new', 'images')
    ### end Alembic commands ###
