"""empty message

Revision ID: 3dc9c5ee9d8
Revises: 3b69f3756b7
Create Date: 2015-03-11 20:27:49.168609

"""

# revision identifiers, used by Alembic.
revision = '3dc9c5ee9d8'
down_revision = '3b69f3756b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name_en',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.add_column('images', sa.Column('file_url', sa.String(length=120), nullable=True))
    op.alter_column('images', 'filename',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'filename',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('images', 'file_url')
    op.alter_column('categories', 'name_en',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    ### end Alembic commands ###
