"""empty message

Revision ID: 4ac528b772e
Revises: 3dc9c5ee9d8
Create Date: 2015-03-25 14:54:49.106037

"""

# revision identifiers, used by Alembic.
revision = '4ac528b772e'
down_revision = '3dc9c5ee9d8'

from alembic import op
import sqlalchemy as sa
import datetime

Session = sa.orm.sessionmaker()

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    cat = op.create_table('categories_new',
                          sa.Column('id', sa.Integer, nullable=False),
                          sa.Column('name', sa.String(64), nullable=False),
                          sa.Column('name_en',
                                    sa.String(64),
                                    nullable=False,
                                    default='EDIT MANUALLY'),
                          sa.Column('active',
                                    sa.Boolean,
                                    nullable=False,
                                    default=False),
                          sa.UniqueConstraint('name'),
                          sa.PrimaryKeyConstraint('id'))

    img = op.create_table('images_new',
                          sa.Column('id', sa.Integer, nullable=False),
                          sa.Column('filename', sa.String(120)),
                          sa.Column('ad_html', sa.Text),
                          sa.Column('location', sa.String(120), nullable=False),
                          sa.Column('url', sa.String(120)),
                          sa.Column('type', sa.Integer, nullable=False),
                          sa.Column('active',
                                    sa.Boolean,
                                    nullable=False,
                                    default=False),
                          sa.Column('timestamp', sa.DateTime, nullable=False),

                          sa.PrimaryKeyConstraint('id'))

    bind = op.get_bind()
    results = bind.execute('select * from categories').fetchall()

    categories = [{'id': r[0],
                   'name': r[1],
                   'name_en': 'EDIT MANUALLY',
                   'active': r[3]} for r in results] # Change to 2 afterwards
    op.bulk_insert(cat, categories)

    results = bind.execute('select * from images').fetchall()
    images = [{'id': r[0],
               'filename': r[1],
               'ad_html': '',
               'location': r[3],
               'url': r[4], # Change to 7 afterwards?
               'type': r[5],
               'active': r[6],
               'timestamp': datetime\
                   .datetime.strptime(r[7],
                                      '%Y-%m-%d %H:%M:%S.%f')} for r in results]
    op.bulk_insert(img, images)

    op.drop_table('categories')
    op.drop_table('images')
    op.rename_table('categories_new', 'categories')
    op.rename_table('images_new', 'images')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    img = op.create_table('images_new',
                          sa.Column('id', sa.Integer, nullable=False),
                          sa.Column('filename', sa.String(120)),
                          sa.Column('file_url', sa.String(120)),
                          sa.Column('location', sa.String(120), nullable=False),
                          sa.Column('url', sa.String(120)),
                          sa.Column('type', sa.Integer, nullable=False),
                          sa.Column('active',
                                    sa.Boolean,
                                    nullable=False,
                                    default=False),
                          sa.Column('timestamp', sa.DateTime, nullable=False),

                          sa.PrimaryKeyConstraint('id'))

    cat = op.create_table('categories_new',
                          sa.Column('id', sa.Integer, nullable=False),
                          sa.Column('name', sa.String(64), nullable=False),
                          sa.Column('name_en',
                                    sa.String(64),
                                    default='EDIT MANUALLY'),
                          sa.Column('active',
                                    sa.Boolean,
                                    nullable=False,
                                    default=False),
                          sa.UniqueConstraint('name'),
                          sa.PrimaryKeyConstraint('id'))

    bind = op.get_bind()

    results = bind.execute('select * from images').fetchall()
    images = [{'id': r[0],
               'filename': r[1],
               'file_url': '',
               'location': r[3],
               'url': r[4], # Change to 7 afterwards?
               'type': r[5],
               'active': r[6],
               'timestamp': datetime\
                   .datetime.strptime(r[7],
                                      '%Y-%m-%d %H:%M:%S.%f')} for r in results]
    op.bulk_insert(img, images)

    results = bind.execute('select * from categories').fetchall()

    categories = [{'id': r[0],
                   'name': r[1],
                   'name_en': 'EDIT MANUALLY',
                   'active': r[3]} for r in results] # Change to 2 afterwards
    op.bulk_insert(cat, categories)

    op.drop_table('images')
    op.drop_table('categories')
    op.rename_table('images_new', 'images')
    op.rename_table('categories_new', 'categories')
    ### end Alembic commands ###
