"""empty message

Revision ID: 5385e5f7663
Revises: 1f134abd84f
Create Date: 2014-07-17 22:27:55.861715

"""

# revision identifiers, used by Alembic.
revision = '5385e5f7663'
down_revision = '1f134abd84f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fb_token', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fb_token')
    ### end Alembic commands ###
